"""Initial schema with core tables

Revision ID: 075e167c8434
Revises: 
Create Date: 2025-10-29 13:10:12.400236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '075e167c8434'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'deleted', name='candidate_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.create_index(op.f('ix_candidates_status'), 'candidates', ['status'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('parsing_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='parsing_status'), nullable=False),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_candidate_id'), 'resumes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resumes_parsing_status'), 'resumes', ['parsing_status'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('role_type', sa.Enum('react', 'python', 'javascript', 'fullstack', name='role_type'), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'abandoned', name='interview_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('ai_model_used', sa.String(length=50), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_candidate_id'), 'interviews', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_interviews_created_at'), 'interviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_interviews_status'), 'interviews', ['status'], unique=False)
    op.create_table('assessment_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('integrity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('skill_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skill_boundary_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('integrity_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_reasoning_gin', 'assessment_results', ['ai_reasoning'], unique=False, postgresql_using='gin')
    op.create_index('idx_skill_scores_gin', 'assessment_results', ['skill_scores'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_assessment_results_interview_id'), 'assessment_results', ['interview_id'], unique=True)
    op.create_table('interview_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('conversation_memory', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_difficulty_level', sa.Enum('warmup', 'standard', 'advanced', name='difficulty_level'), nullable=False),
    sa.Column('questions_asked_count', sa.Integer(), nullable=False),
    sa.Column('skill_boundaries_identified', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('progression_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_memory_gin', 'interview_sessions', ['conversation_memory'], unique=False, postgresql_using='gin')
    op.create_index('idx_progression_state_gin', 'interview_sessions', ['progression_state'], unique=False, postgresql_using='gin')
    op.create_index('idx_skill_boundaries_gin', 'interview_sessions', ['skill_boundaries_identified'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_interview_sessions_interview_id'), 'interview_sessions', ['interview_id'], unique=True)
    op.create_index(op.f('ix_interview_sessions_last_activity_at'), 'interview_sessions', ['last_activity_at'], unique=False)
    op.create_table('interview_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.Enum('ai_question', 'candidate_response', name='message_type'), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('content_audio_url', sa.Text(), nullable=True),
    sa.Column('audio_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('audio_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interview_messages_sequence', 'interview_messages', ['interview_id', 'sequence_number'], unique=False)
    op.create_index('idx_message_metadata_gin', 'interview_messages', ['message_metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_interview_messages_interview_id'), 'interview_messages', ['interview_id'], unique=False)
    op.create_index(op.f('ix_interview_messages_session_id'), 'interview_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_messages_session_id'), table_name='interview_messages')
    op.drop_index(op.f('ix_interview_messages_interview_id'), table_name='interview_messages')
    op.drop_index('idx_message_metadata_gin', table_name='interview_messages', postgresql_using='gin')
    op.drop_index('idx_interview_messages_sequence', table_name='interview_messages')
    op.drop_table('interview_messages')
    op.drop_index(op.f('ix_interview_sessions_last_activity_at'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_interview_id'), table_name='interview_sessions')
    op.drop_index('idx_skill_boundaries_gin', table_name='interview_sessions', postgresql_using='gin')
    op.drop_index('idx_progression_state_gin', table_name='interview_sessions', postgresql_using='gin')
    op.drop_index('idx_conversation_memory_gin', table_name='interview_sessions', postgresql_using='gin')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_assessment_results_interview_id'), table_name='assessment_results')
    op.drop_index('idx_skill_scores_gin', table_name='assessment_results', postgresql_using='gin')
    op.drop_index('idx_ai_reasoning_gin', table_name='assessment_results', postgresql_using='gin')
    op.drop_table('assessment_results')
    op.drop_index(op.f('ix_interviews_status'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_created_at'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_candidate_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_resumes_parsing_status'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_candidate_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_candidates_status'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
    
    # Drop enum types (not auto-generated by Alembic)
    op.execute('DROP TYPE IF EXISTS message_type')
    op.execute('DROP TYPE IF EXISTS difficulty_level')
    op.execute('DROP TYPE IF EXISTS interview_status')
    op.execute('DROP TYPE IF EXISTS role_type')
    op.execute('DROP TYPE IF EXISTS parsing_status')
    op.execute('DROP TYPE IF EXISTS candidate_status')
