"""add_video_interview_fields_epic_02

Revision ID: 4839d6236216
Revises: 173e256bc347
Create Date: 2025-11-01 21:58:23.308832

Purpose: Add database support for Epic 02 video interview features
- Tech check results storage (audio/camera tests) in interviews.tech_check_metadata
- Video recording URLs and consent tracking in interviews table
- Video metadata table (video_recordings) for detailed recording information
- Soft delete capability for GDPR compliance
- GIN indexes on JSONB columns for flexible querying

Backward Compatibility: All new fields are nullable (no breaking changes)
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4839d6236216'
down_revision: Union[str, Sequence[str], None] = '173e256bc347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create video_recording_status enum type first
    video_recording_status_enum = postgresql.ENUM(
        'not_recorded', 'recording', 'completed', 'failed', 'deleted',
        name='video_recording_status'
    )
    video_recording_status_enum.create(op.get_bind(), checkfirst=True)
    
    # Create video_recordings table for video metadata tracking
    # Stores upload status, file metadata, and supports soft delete (GDPR)
    op.create_table('video_recordings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),  # Supabase Storage path
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),  # e.g., "1280x720"
    sa.Column('bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('codec', sa.String(length=50), nullable=True),  # e.g., "H.264"
    sa.Column('upload_started_at', sa.DateTime(), nullable=False),
    sa.Column('upload_completed_at', sa.DateTime(), nullable=True),  # NULL if incomplete
    sa.Column('deleted_at', sa.DateTime(), nullable=True),  # Soft delete timestamp
    sa.Column('recording_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),  # Quality metrics, chunk info
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),  # Delete video with interview
    sa.PrimaryKeyConstraint('id')
    )
    
    # Indexes for video_recordings table
    op.create_index(op.f('ix_video_recordings_deleted_at'), 'video_recordings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_video_recordings_interview_id'), 'video_recordings', ['interview_id'], unique=True)  # One-to-one
    op.create_index(op.f('ix_video_recordings_upload_completed_at'), 'video_recordings', ['upload_completed_at'], unique=False)
    
    # GIN index on recording_metadata for flexible JSONB querying
    op.create_index(
        'ix_video_recordings_recording_metadata_gin',
        'video_recordings',
        ['recording_metadata'],
        unique=False,
        postgresql_using='gin'
    )
    
    # Add video interview fields to interviews table
    # All fields nullable for backward compatibility with existing interviews
    op.add_column('interviews', sa.Column('tech_check_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))  # Audio/camera test results
    op.add_column('interviews', sa.Column('video_recording_url', sa.String(), nullable=True))  # Supabase Storage URL
    op.add_column('interviews', sa.Column('video_recording_consent', sa.Boolean(), nullable=False, server_default='false'))  # GDPR consent flag
    op.add_column('interviews', sa.Column('video_recording_status', sa.Enum('not_recorded', 'recording', 'completed', 'failed', 'deleted', name='video_recording_status'), nullable=True))
    
    # GIN index on tech_check_metadata for flexible JSONB querying
    op.create_index(
        'ix_interviews_tech_check_metadata_gin',
        'interviews',
        ['tech_check_metadata'],
        unique=False,
        postgresql_using='gin'
    )
    
    # B-tree index on video_recording_status for filtering
    op.create_index(
        op.f('ix_interviews_video_recording_status'),
        'interviews',
        ['video_recording_status'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes on interviews table
    op.drop_index(op.f('ix_interviews_video_recording_status'), table_name='interviews')
    op.drop_index('ix_interviews_tech_check_metadata_gin', table_name='interviews')
    
    # Drop video interview columns from interviews table
    op.drop_column('interviews', 'video_recording_status')
    op.drop_column('interviews', 'video_recording_consent')
    op.drop_column('interviews', 'video_recording_url')
    op.drop_column('interviews', 'tech_check_metadata')
    
    # Drop video recording status enum type
    sa.Enum(name='video_recording_status').drop(op.get_bind(), checkfirst=True)
    
    # Drop indexes on video_recordings table
    op.drop_index('ix_video_recordings_recording_metadata_gin', table_name='video_recordings')
    op.drop_index(op.f('ix_video_recordings_upload_completed_at'), table_name='video_recordings')
    op.drop_index(op.f('ix_video_recordings_interview_id'), table_name='video_recordings')
    op.drop_index(op.f('ix_video_recordings_deleted_at'), table_name='video_recordings')
    
    # Drop video_recordings table
    op.drop_table('video_recordings')
    # ### end Alembic commands ###
